name: RIS_gravity_inversion
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - polartoolkit>=0.7
  - invert4geom>=0.11
  - pyogrio
  - esmpy
  - xesmf
  - cmocean
  - ipykernel
  - jupyterlab_execute_time
  - pre-commit
  - pylint
  - pip
  - pip:
      - snakeviz
      - kneebow
