name: RIS_gravity_inversion
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pygmt
  - geopandas
  - geoviews
  - numpy
  - pandas
  - snakeviz
  - scipy
  - matplotlib
  - pyvista
  - pyvista-xarray
  - harmonica
  - verde
  - xarray
  - tqdm
  - rioxarray
  - seaborn
  - ipykernel
  # - cmocean
  - numba
  - optuna
  - plotly
  - hvplot
  - jupyter_bokeh
  - jupyterlab
  - isort
  - pytest
  - pytest-cov
  - python-dotenv
  - pip
  - pip:
    - numba-progress
    - tqdm-joblib
    - jupyter-server-proxy
    - trame
    - flake8-pyproject
    - black[jupyter]
    - constrained-linear-regression
    - --editable ../antarctic_plots
    - --editable .