# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sample_geometry.ui'
#
# Created: Fri Nov 22 16:13:48 2019
#      by: PyQt5 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(346, 900)
        MainWindow.setMinimumSize(QtCore.QSize(346, 900))
        MainWindow.setMaximumSize(QtCore.QSize(346, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_input_gravity_file = QtWidgets.QLabel(self.centralwidget)
        self.label_input_gravity_file.setGeometry(QtCore.QRect(5, 25, 205, 20))
        self.label_input_gravity_file.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_gravity_file.setObjectName(_fromUtf8("label_input_gravity_file"))
        self.lineinput_gravity_file = QtWidgets.QLineEdit(self.centralwidget)
        self.lineinput_gravity_file.setGeometry(QtCore.QRect(5, 5, 205, 20))
        self.lineinput_gravity_file.setObjectName(_fromUtf8("lineinput_gravity_file"))
        self.linenumber_gravity_data = QtWidgets.QLineEdit(self.centralwidget)
        self.linenumber_gravity_data.setGeometry(QtCore.QRect(230, 5, 110, 20))
        self.linenumber_gravity_data.setObjectName(_fromUtf8("linenumber_gravity_data"))
        self.labelnumber_gravity_data = QtWidgets.QLabel(self.centralwidget)
        self.labelnumber_gravity_data.setGeometry(QtCore.QRect(230, 25, 110, 20))
        self.labelnumber_gravity_data.setAlignment(QtCore.Qt.AlignCenter)
        self.labelnumber_gravity_data.setObjectName(_fromUtf8("labelnumber_gravity_data"))
        self.label_input_ice_layer = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer.setGeometry(QtCore.QRect(5, 70, 205, 20))
        self.label_input_ice_layer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer.setObjectName(_fromUtf8("label_input_ice_layer"))
        self.lineinput_ice_layer = QtWidgets.QLineEdit(self.centralwidget)
        self.lineinput_ice_layer.setGeometry(QtCore.QRect(5, 50, 205, 20))
        self.lineinput_ice_layer.setObjectName(_fromUtf8("lineinput_ice_layer"))
        self.labelnumber_ice_points = QtWidgets.QLabel(self.centralwidget)
        self.labelnumber_ice_points.setGeometry(QtCore.QRect(230, 70, 110, 20))
        self.labelnumber_ice_points.setAlignment(QtCore.Qt.AlignCenter)
        self.labelnumber_ice_points.setObjectName(_fromUtf8("labelnumber_ice_points"))
        self.linenumber_ice_layer = QtWidgets.QLineEdit(self.centralwidget)
        self.linenumber_ice_layer.setGeometry(QtCore.QRect(230, 50, 110, 20))
        self.linenumber_ice_layer.setObjectName(_fromUtf8("linenumber_ice_layer"))
        self.label_input_ice_layer_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_2.setGeometry(QtCore.QRect(5, 115, 205, 20))
        self.label_input_ice_layer_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_2.setObjectName(_fromUtf8("label_input_ice_layer_2"))
        self.linenumber_water_layer = QtWidgets.QLineEdit(self.centralwidget)
        self.linenumber_water_layer.setGeometry(QtCore.QRect(230, 95, 110, 20))
        self.linenumber_water_layer.setObjectName(_fromUtf8("linenumber_water_layer"))
        self.lineinput_water_layer = QtWidgets.QLineEdit(self.centralwidget)
        self.lineinput_water_layer.setGeometry(QtCore.QRect(5, 95, 205, 20))
        self.lineinput_water_layer.setObjectName(_fromUtf8("lineinput_water_layer"))
        self.labelnumber_water_points = QtWidgets.QLabel(self.centralwidget)
        self.labelnumber_water_points.setGeometry(QtCore.QRect(230, 115, 110, 20))
        self.labelnumber_water_points.setAlignment(QtCore.Qt.AlignCenter)
        self.labelnumber_water_points.setObjectName(_fromUtf8("labelnumber_water_points"))
        self.label_input_ice_layer_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_3.setGeometry(QtCore.QRect(5, 160, 205, 20))
        self.label_input_ice_layer_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_3.setObjectName(_fromUtf8("label_input_ice_layer_3"))
        self.linenumber_layer1 = QtWidgets.QLineEdit(self.centralwidget)
        self.linenumber_layer1.setGeometry(QtCore.QRect(230, 140, 110, 20))
        self.linenumber_layer1.setObjectName(_fromUtf8("linenumber_layer1"))
        self.lineinput_layer1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineinput_layer1.setGeometry(QtCore.QRect(5, 140, 205, 20))
        self.lineinput_layer1.setObjectName(_fromUtf8("lineinput_layer1"))
        self.labelnumber_ice_points_3 = QtWidgets.QLabel(self.centralwidget)
        self.labelnumber_ice_points_3.setGeometry(QtCore.QRect(230, 160, 110, 20))
        self.labelnumber_ice_points_3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelnumber_ice_points_3.setObjectName(_fromUtf8("labelnumber_ice_points_3"))
        self.label_input_ice_layer_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_4.setGeometry(QtCore.QRect(5, 205, 205, 20))
        self.label_input_ice_layer_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_4.setObjectName(_fromUtf8("label_input_ice_layer_4"))
        self.linenumber_layer2 = QtWidgets.QLineEdit(self.centralwidget)
        self.linenumber_layer2.setGeometry(QtCore.QRect(230, 185, 110, 20))
        self.linenumber_layer2.setObjectName(_fromUtf8("linenumber_layer2"))
        self.lineinput_layer2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineinput_layer2.setGeometry(QtCore.QRect(5, 185, 205, 20))
        self.lineinput_layer2.setObjectName(_fromUtf8("lineinput_layer2"))
        self.labelnumber_ice_points_4 = QtWidgets.QLabel(self.centralwidget)
        self.labelnumber_ice_points_4.setGeometry(QtCore.QRect(230, 205, 110, 20))
        self.labelnumber_ice_points_4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelnumber_ice_points_4.setObjectName(_fromUtf8("labelnumber_ice_points_4"))
        self.label_input_resolution_ice_layer = QtWidgets.QLabel(self.centralwidget)
        self.label_input_resolution_ice_layer.setGeometry(QtCore.QRect(5, 270, 221, 20))
        self.label_input_resolution_ice_layer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_input_resolution_ice_layer.setObjectName(_fromUtf8("label_input_resolution_ice_layer"))
        self.lineice_layer_resolution = QtWidgets.QLineEdit(self.centralwidget)
        self.lineice_layer_resolution.setGeometry(QtCore.QRect(230, 270, 110, 20))
        self.lineice_layer_resolution.setObjectName(_fromUtf8("lineice_layer_resolution"))
        self.linewater_layer_resolution = QtWidgets.QLineEdit(self.centralwidget)
        self.linewater_layer_resolution.setGeometry(QtCore.QRect(230, 300, 110, 20))
        self.linewater_layer_resolution.setObjectName(_fromUtf8("linewater_layer_resolution"))
        self.label_input_resolution_water_layer = QtWidgets.QLabel(self.centralwidget)
        self.label_input_resolution_water_layer.setGeometry(QtCore.QRect(5, 300, 221, 20))
        self.label_input_resolution_water_layer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_input_resolution_water_layer.setObjectName(_fromUtf8("label_input_resolution_water_layer"))
        self.linelayer1_resolution = QtWidgets.QLineEdit(self.centralwidget)
        self.linelayer1_resolution.setGeometry(QtCore.QRect(230, 330, 110, 20))
        self.linelayer1_resolution.setObjectName(_fromUtf8("linelayer1_resolution"))
        self.label_input_resolution_layer_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_resolution_layer_1.setGeometry(QtCore.QRect(5, 330, 221, 20))
        self.label_input_resolution_layer_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_input_resolution_layer_1.setObjectName(_fromUtf8("label_input_resolution_layer_1"))
        self.linelayer2_resolution = QtWidgets.QLineEdit(self.centralwidget)
        self.linelayer2_resolution.setGeometry(QtCore.QRect(230, 360, 110, 20))
        self.linelayer2_resolution.setObjectName(_fromUtf8("linelayer2_resolution"))
        self.label_input_resolution_layer_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_resolution_layer_2.setGeometry(QtCore.QRect(5, 360, 221, 20))
        self.label_input_resolution_layer_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_input_resolution_layer_2.setObjectName(_fromUtf8("label_input_resolution_layer_2"))
        self.pushButton_plotinputdata = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plotinputdata.setGeometry(QtCore.QRect(5, 420, 335, 50))
        font = QtGui.QFont()

        font.setPointSize(12)
        self.pushButton_plotinputdata.setFont(font)
        self.pushButton_plotinputdata.setAutoFillBackground(False)
        self.pushButton_plotinputdata.setStyleSheet(_fromUtf8("background-color: rgb(157, 157, 157);"))
        self.pushButton_plotinputdata.setObjectName(_fromUtf8("pushButton_plotinputdata"))
        self.linegravity_data_resolution = QtWidgets.QLineEdit(self.centralwidget)
        self.linegravity_data_resolution.setGeometry(QtCore.QRect(230, 240, 110, 20))
        self.linegravity_data_resolution.setObjectName(_fromUtf8("linegravity_data_resolution"))
        self.label_input_resolution_garvity_data = QtWidgets.QLabel(self.centralwidget)
        self.label_input_resolution_garvity_data.setGeometry(QtCore.QRect(5, 240, 221, 20))
        self.label_input_resolution_garvity_data.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_input_resolution_garvity_data.setObjectName(_fromUtf8("label_input_resolution_garvity_data"))
        self.comboBox_detrending = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_detrending.setGeometry(QtCore.QRect(170, 390, 170, 22))
        self.comboBox_detrending.setObjectName(_fromUtf8("comboBox_detrending"))
        self.comboBox_detrending.addItem(_fromUtf8(""))
        self.comboBox_detrending.addItem(_fromUtf8(""))
        self.label_detrending = QtWidgets.QLabel(self.centralwidget)
        self.label_detrending.setGeometry(QtCore.QRect(5, 390, 181, 20))
        self.label_detrending.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_detrending.setObjectName(_fromUtf8("label_detrending"))
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(5, 820, 335, 35))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.pushButton_run_inversion = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run_inversion.setEnabled(False)
        self.pushButton_run_inversion.setGeometry(QtCore.QRect(5, 684, 335, 50))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.pushButton_run_inversion.setFont(font)
        self.pushButton_run_inversion.setAutoFillBackground(False)
        self.pushButton_run_inversion.setStyleSheet(_fromUtf8("background-color: rgb(157, 157, 157);"))
        self.pushButton_run_inversion.setObjectName(_fromUtf8("pushButton_run_inversion"))
        self.linebathymetry_variation = QtWidgets.QLineEdit(self.centralwidget)
        self.linebathymetry_variation.setGeometry(QtCore.QRect(25, 480, 125, 20))
        self.linebathymetry_variation.setAlignment(QtCore.Qt.AlignCenter)
        self.linebathymetry_variation.setObjectName(_fromUtf8("linebathymetry_variation"))
        self.linebasement_variation = QtWidgets.QLineEdit(self.centralwidget)
        self.linebasement_variation.setGeometry(QtCore.QRect(195, 480, 125, 20))
        self.linebasement_variation.setAlignment(QtCore.Qt.AlignCenter)
        self.linebasement_variation.setObjectName(_fromUtf8("linebasement_variation"))
        self.label_input_ice_layer_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_5.setGeometry(QtCore.QRect(5, 500, 165, 20))
        self.label_input_ice_layer_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_5.setObjectName(_fromUtf8("label_input_ice_layer_5"))
        self.label_input_ice_layer_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_6.setGeometry(QtCore.QRect(175, 500, 165, 20))
        self.label_input_ice_layer_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_6.setObjectName(_fromUtf8("label_input_ice_layer_6"))
        self.label_input_ice_layer_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_7.setGeometry(QtCore.QRect(5, 540, 165, 20))
        self.label_input_ice_layer_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_7.setObjectName(_fromUtf8("label_input_ice_layer_7"))
        self.label_input_ice_layer_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_8.setGeometry(QtCore.QRect(175, 540, 165, 20))
        self.label_input_ice_layer_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_8.setObjectName(_fromUtf8("label_input_ice_layer_8"))
        self.linebathymetry_constraints = QtWidgets.QLineEdit(self.centralwidget)
        self.linebathymetry_constraints.setGeometry(QtCore.QRect(25, 520, 125, 20))
        self.linebathymetry_constraints.setAlignment(QtCore.Qt.AlignCenter)
        self.linebathymetry_constraints.setObjectName(_fromUtf8("linebathymetry_constraints"))
        self.linebasement_constraints = QtWidgets.QLineEdit(self.centralwidget)
        self.linebasement_constraints.setGeometry(QtCore.QRect(195, 520, 125, 20))
        self.linebasement_constraints.setAlignment(QtCore.Qt.AlignCenter)
        self.linebasement_constraints.setObjectName(_fromUtf8("linebasement_constraints"))
        self.label_input_ice_layer_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_9.setGeometry(QtCore.QRect(5, 580, 165, 20))
        self.label_input_ice_layer_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_9.setObjectName(_fromUtf8("label_input_ice_layer_9"))
        self.label_input_ice_layer_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_10.setGeometry(QtCore.QRect(175, 580, 165, 20))
        self.label_input_ice_layer_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_10.setObjectName(_fromUtf8("label_input_ice_layer_10"))
        self.lineleast_squares = QtWidgets.QLineEdit(self.centralwidget)
        self.lineleast_squares.setGeometry(QtCore.QRect(25, 560, 125, 20))
        self.lineleast_squares.setAlignment(QtCore.Qt.AlignCenter)
        self.lineleast_squares.setObjectName(_fromUtf8("lineleast_squares"))
        self.lineleast_squares_tolerance = QtWidgets.QLineEdit(self.centralwidget)
        self.lineleast_squares_tolerance.setGeometry(QtCore.QRect(195, 560, 125, 20))
        self.lineleast_squares_tolerance.setAlignment(QtCore.Qt.AlignCenter)
        self.lineleast_squares_tolerance.setObjectName(_fromUtf8("lineleast_squares_tolerance"))
        self.label_input_ice_layer_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_11.setGeometry(QtCore.QRect(170, 620, 165, 20))
        self.label_input_ice_layer_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_11.setObjectName(_fromUtf8("label_input_ice_layer_11"))
        self.label_input_ice_layer_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_12.setGeometry(QtCore.QRect(5, 620, 165, 20))
        self.label_input_ice_layer_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_12.setObjectName(_fromUtf8("label_input_ice_layer_12"))
        self.linedensity_shift = QtWidgets.QLineEdit(self.centralwidget)
        self.linedensity_shift.setGeometry(QtCore.QRect(195, 600, 125, 20))
        self.linedensity_shift.setAlignment(QtCore.Qt.AlignCenter)
        self.linedensity_shift.setObjectName(_fromUtf8("linedensity_shift"))
        self.linemaximum_iterations = QtWidgets.QLineEdit(self.centralwidget)
        self.linemaximum_iterations.setGeometry(QtCore.QRect(25, 600, 125, 20))
        self.linemaximum_iterations.setAlignment(QtCore.Qt.AlignCenter)
        self.linemaximum_iterations.setObjectName(_fromUtf8("linemaximum_iterations"))
        self.messagebox = QtWidgets.QTextEdit(self.centralwidget)
        self.messagebox.setGeometry(QtCore.QRect(5, 744, 335, 70))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.messagebox.setFont(font)
        self.messagebox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.messagebox.setObjectName(_fromUtf8("messagebox"))
        self.lineminimum_sediment_thickness = QtWidgets.QLineEdit(self.centralwidget)
        self.lineminimum_sediment_thickness.setGeometry(QtCore.QRect(195, 640, 125, 20))
        self.lineminimum_sediment_thickness.setAlignment(QtCore.Qt.AlignCenter)
        self.lineminimum_sediment_thickness.setObjectName(_fromUtf8("lineminimum_sediment_thickness"))
        self.linedensity_inversion = QtWidgets.QLineEdit(self.centralwidget)
        self.linedensity_inversion.setGeometry(QtCore.QRect(25, 640, 125, 20))
        self.linedensity_inversion.setAlignment(QtCore.Qt.AlignCenter)
        self.linedensity_inversion.setObjectName(_fromUtf8("linedensity_inversion"))
        self.label_input_ice_layer_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_13.setGeometry(QtCore.QRect(5, 660, 165, 20))
        self.label_input_ice_layer_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_13.setObjectName(_fromUtf8("label_input_ice_layer_13"))
        self.label_input_ice_layer_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_14.setGeometry(QtCore.QRect(170, 660, 165, 20))
        self.label_input_ice_layer_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_14.setObjectName(_fromUtf8("label_input_ice_layer_14"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 346, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionInput_gravity_data = QtWidgets.QAction(MainWindow)
        self.actionInput_gravity_data.setObjectName(_fromUtf8("actionInput_gravity_data"))
        self.actionExit_program = QtWidgets.QAction(MainWindow)
        self.actionExit_program.setObjectName(_fromUtf8("actionExit_program"))
        self.actionInput_top_ice_geometry = QtWidgets.QAction(MainWindow)
        self.actionInput_top_ice_geometry.setObjectName(_fromUtf8("actionInput_top_ice_geometry"))
        self.actionInput_bottom_ice_geometry = QtWidgets.QAction(MainWindow)
        self.actionInput_bottom_ice_geometry.setObjectName(_fromUtf8("actionInput_bottom_ice_geometry"))
        self.actionInput_layer_1_geometry = QtWidgets.QAction(MainWindow)
        self.actionInput_layer_1_geometry.setObjectName(_fromUtf8("actionInput_layer_1_geometry"))
        self.actionInput_layer_2_geometry = QtWidgets.QAction(MainWindow)
        self.actionInput_layer_2_geometry.setObjectName(_fromUtf8("actionInput_layer_2_geometry"))
        self.actionSave_output_file = QtWidgets.QAction(MainWindow)
        self.actionSave_output_file.setEnabled(False)
        self.actionSave_output_file.setObjectName(_fromUtf8("actionSave_output_file"))
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionMAnual = QtWidgets.QAction(MainWindow)
        self.actionMAnual.setObjectName(_fromUtf8("actionMAnual"))
        self.actionRun_density_inversion = QtWidgets.QAction(MainWindow)
        self.actionRun_density_inversion.setEnabled(False)
        self.actionRun_density_inversion.setObjectName(_fromUtf8("actionRun_density_inversion"))
        self.actionClear_memory = QtWidgets.QAction(MainWindow)
        self.actionClear_memory.setObjectName(_fromUtf8("actionClear_memory"))
        self.menuFile.addAction(self.actionInput_gravity_data)
        self.menuFile.addAction(self.actionInput_top_ice_geometry)
        self.menuFile.addAction(self.actionInput_bottom_ice_geometry)
        self.menuFile.addAction(self.actionInput_layer_1_geometry)
        self.menuFile.addAction(self.actionInput_layer_2_geometry)
        self.menuFile.addAction(self.actionRun_density_inversion)
        self.menuFile.addAction(self.actionSave_output_file)
        self.menuFile.addAction(self.actionClear_memory)
        self.menuFile.addAction(self.actionExit_program)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionMAnual)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_input_gravity_file.setText(_translate("MainWindow", "Input gravity data file", None))
        self.labelnumber_gravity_data.setText(_translate("MainWindow", "Size of gravity dataset", None))
        self.label_input_ice_layer.setText(_translate("MainWindow", "Input ice layer file", None))
        self.labelnumber_ice_points.setText(_translate("MainWindow", "Points in ice layer", None))
        self.label_input_ice_layer_2.setText(_translate("MainWindow", "Input water layer file", None))
        self.labelnumber_water_points.setText(_translate("MainWindow", "Points in water layer", None))
        self.label_input_ice_layer_3.setText(_translate("MainWindow", "Input layer 1 file", None))
        self.labelnumber_ice_points_3.setText(_translate("MainWindow", "Points in layer 1", None))
        self.label_input_ice_layer_4.setText(_translate("MainWindow", "Input layer 2 file", None))
        self.labelnumber_ice_points_4.setText(_translate("MainWindow", "Points in layer 2", None))
        self.label_input_resolution_ice_layer.setText(_translate("MainWindow", "Input spatial resolution of ice layer (m) -->", None))
        self.label_input_resolution_water_layer.setText(_translate("MainWindow", "Input spatial resolution of water layer (m) -->", None))
        self.label_input_resolution_layer_1.setText(_translate("MainWindow", "Input spatial resolution of layer 1 (m) -->", None))
        self.label_input_resolution_layer_2.setText(_translate("MainWindow", "Input spatial resolution of layer 2 (m) -->", None))
        self.pushButton_plotinputdata.setText(_translate("MainWindow", "Grid and plot input data", None))
        self.label_input_resolution_garvity_data.setText(_translate("MainWindow", "Input spatial resolution of ice layer (m) -->", None))
        self.comboBox_detrending.setItemText(0, _translate("MainWindow", "Constant value", None))
        self.comboBox_detrending.setItemText(1, _translate("MainWindow", "Linear trend", None))
        self.label_detrending.setText(_translate("MainWindow", "Select model for regional field -->", None))
        self.pushButton_run_inversion.setText(_translate("MainWindow", "Run inversion", None))
        self.linebathymetry_variation.setText(_translate("MainWindow", "1000", None))
        self.linebasement_variation.setText(_translate("MainWindow", "1000", None))
        self.label_input_ice_layer_5.setText(_translate("MainWindow", "Bathymetry variation (m)", None))
        self.label_input_ice_layer_6.setText(_translate("MainWindow", "Basement variation (m)", None))
        self.label_input_ice_layer_7.setText(_translate("MainWindow", "Bathymetry constraints (m)", None))
        self.label_input_ice_layer_8.setText(_translate("MainWindow", "Basement constraints (m)", None))
        self.linebathymetry_constraints.setText(_translate("MainWindow", "100", None))
        self.linebasement_constraints.setText(_translate("MainWindow", "100", None))
        self.label_input_ice_layer_9.setText(_translate("MainWindow", "Least-squares norm", None))
        self.label_input_ice_layer_10.setText(_translate("MainWindow", "Tolerance on least-squares norm", None))
        self.lineleast_squares.setText(_translate("MainWindow", "0.001", None))
        self.lineleast_squares_tolerance.setText(_translate("MainWindow", "0.02", None))
        self.label_input_ice_layer_11.setText(_translate("MainWindow", "Density inversion filtering", None))
        self.label_input_ice_layer_12.setText(_translate("MainWindow", "Maximum number of iterations", None))
        self.linedensity_shift.setText(_translate("MainWindow", "0", None))
        self.linemaximum_iterations.setText(_translate("MainWindow", "50", None))
        self.messagebox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p></body></html>", None))
        self.lineminimum_sediment_thickness.setText(_translate("MainWindow", "100", None))
        self.linedensity_inversion.setText(_translate("MainWindow", "0.0", None))
        self.label_input_ice_layer_13.setText(_translate("MainWindow", "Density inversion range (g/cm^3)", None))
        self.label_input_ice_layer_14.setText(_translate("MainWindow", "Minimum sediment thickness", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionInput_gravity_data.setText(_translate("MainWindow", "Input gravity data", None))
        self.actionExit_program.setText(_translate("MainWindow", "Exit program", None))
        self.actionInput_top_ice_geometry.setText(_translate("MainWindow", "Input ice geometry", None))
        self.actionInput_bottom_ice_geometry.setText(_translate("MainWindow", "Input water geometry", None))
        self.actionInput_layer_1_geometry.setText(_translate("MainWindow", "Input layer 1 geometry", None))
        self.actionInput_layer_2_geometry.setText(_translate("MainWindow", "Input layer 2 geometry", None))
        self.actionSave_output_file.setText(_translate("MainWindow", "Save output file", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionMAnual.setText(_translate("MainWindow", "Manual", None))
        self.actionRun_density_inversion.setText(_translate("MainWindow", "Run density inversion", None))
        self.actionClear_memory.setText(_translate("MainWindow", "Clear memory", None))

