# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grav_bathy_inversion_GUI_geometry.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 575)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_input_gravity_data_file = QtWidgets.QLineEdit(self.centralwidget)
        self.line_input_gravity_data_file.setGeometry(QtCore.QRect(20, 10, 231, 21))
        self.line_input_gravity_data_file.setObjectName("line_input_gravity_data_file")
        self.label_input_gravity_data_file = QtWidgets.QLabel(self.centralwidget)
        self.label_input_gravity_data_file.setGeometry(QtCore.QRect(20, 30, 231, 16))
        self.label_input_gravity_data_file.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_gravity_data_file.setObjectName("label_input_gravity_data_file")
        self.line_input_ice_surface_file = QtWidgets.QLineEdit(self.centralwidget)
        self.line_input_ice_surface_file.setGeometry(QtCore.QRect(20, 60, 231, 21))
        self.line_input_ice_surface_file.setObjectName("line_input_ice_surface_file")
        self.label_ice_surface_file = QtWidgets.QLabel(self.centralwidget)
        self.label_ice_surface_file.setGeometry(QtCore.QRect(20, 80, 231, 16))
        self.label_ice_surface_file.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ice_surface_file.setObjectName("label_ice_surface_file")
        self.line_input_water_surface_file = QtWidgets.QLineEdit(self.centralwidget)
        self.line_input_water_surface_file.setGeometry(QtCore.QRect(20, 110, 231, 21))
        self.line_input_water_surface_file.setObjectName("line_input_water_surface_file")
        self.label_input_water_surface_file = QtWidgets.QLabel(self.centralwidget)
        self.label_input_water_surface_file.setGeometry(QtCore.QRect(20, 130, 231, 16))
        self.label_input_water_surface_file.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_water_surface_file.setObjectName("label_input_water_surface_file")
        self.line_input_bathymetry_file = QtWidgets.QLineEdit(self.centralwidget)
        self.line_input_bathymetry_file.setGeometry(QtCore.QRect(20, 160, 231, 21))
        self.line_input_bathymetry_file.setObjectName("line_input_bathymetry_file")
        self.label_bathymetry_file = QtWidgets.QLabel(self.centralwidget)
        self.label_bathymetry_file.setGeometry(QtCore.QRect(20, 180, 231, 16))
        self.label_bathymetry_file.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bathymetry_file.setObjectName("label_bathymetry_file")
        self.line_input_basement_surface_file = QtWidgets.QLineEdit(self.centralwidget)
        self.line_input_basement_surface_file.setGeometry(QtCore.QRect(20, 210, 231, 21))
        self.line_input_basement_surface_file.setObjectName("line_input_basement_surface_file")
        self.label_input_basement_file = QtWidgets.QLabel(self.centralwidget)
        self.label_input_basement_file.setGeometry(QtCore.QRect(20, 230, 231, 16))
        self.label_input_basement_file.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_basement_file.setObjectName("label_input_basement_file")
        self.line_input_moho_file = QtWidgets.QLineEdit(self.centralwidget)
        self.line_input_moho_file.setGeometry(QtCore.QRect(20, 260, 231, 21))
        self.line_input_moho_file.setText("")
        self.line_input_moho_file.setObjectName("line_input_moho_file")
        self.label_input_moho_file = QtWidgets.QLabel(self.centralwidget)
        self.label_input_moho_file.setGeometry(QtCore.QRect(20, 280, 231, 16))
        self.label_input_moho_file.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_moho_file.setObjectName("label_input_moho_file")
        self.line_gravity_size = QtWidgets.QLineEdit(self.centralwidget)
        self.line_gravity_size.setGeometry(QtCore.QRect(270, 10, 71, 21))
        self.line_gravity_size.setObjectName("line_gravity_size")
        self.label_gravity_size = QtWidgets.QLabel(self.centralwidget)
        self.label_gravity_size.setGeometry(QtCore.QRect(260, 30, 91, 16))
        self.label_gravity_size.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gravity_size.setObjectName("label_gravity_size")
        self.label_bathymetry_size = QtWidgets.QLabel(self.centralwidget)
        self.label_bathymetry_size.setGeometry(QtCore.QRect(260, 180, 91, 16))
        self.label_bathymetry_size.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bathymetry_size.setObjectName("label_bathymetry_size")
        self.line_bathymetry_size = QtWidgets.QLineEdit(self.centralwidget)
        self.line_bathymetry_size.setGeometry(QtCore.QRect(270, 160, 71, 21))
        self.line_bathymetry_size.setObjectName("line_bathymetry_size")
        self.label_ice_size = QtWidgets.QLabel(self.centralwidget)
        self.label_ice_size.setGeometry(QtCore.QRect(260, 80, 91, 16))
        self.label_ice_size.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ice_size.setObjectName("label_ice_size")
        self.line_ice_size = QtWidgets.QLineEdit(self.centralwidget)
        self.line_ice_size.setGeometry(QtCore.QRect(270, 60, 71, 21))
        self.line_ice_size.setObjectName("line_ice_size")
        self.label_water_size = QtWidgets.QLabel(self.centralwidget)
        self.label_water_size.setGeometry(QtCore.QRect(260, 130, 91, 16))
        self.label_water_size.setAlignment(QtCore.Qt.AlignCenter)
        self.label_water_size.setObjectName("label_water_size")
        self.line_water_size = QtWidgets.QLineEdit(self.centralwidget)
        self.line_water_size.setGeometry(QtCore.QRect(270, 110, 71, 21))
        self.line_water_size.setObjectName("line_water_size")
        self.label_basement_size = QtWidgets.QLabel(self.centralwidget)
        self.label_basement_size.setGeometry(QtCore.QRect(260, 230, 91, 16))
        self.label_basement_size.setAlignment(QtCore.Qt.AlignCenter)
        self.label_basement_size.setObjectName("label_basement_size")
        self.line_basement_size = QtWidgets.QLineEdit(self.centralwidget)
        self.line_basement_size.setGeometry(QtCore.QRect(270, 210, 71, 21))
        self.line_basement_size.setObjectName("line_basement_size")
        self.label_moho_size = QtWidgets.QLabel(self.centralwidget)
        self.label_moho_size.setGeometry(QtCore.QRect(260, 280, 91, 16))
        self.label_moho_size.setAlignment(QtCore.Qt.AlignCenter)
        self.label_moho_size.setObjectName("label_moho_size")
        self.line_moho_size = QtWidgets.QLineEdit(self.centralwidget)
        self.line_moho_size.setGeometry(QtCore.QRect(270, 260, 71, 21))
        self.line_moho_size.setObjectName("line_moho_size")
        self.pushButton_plot_input_data = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plot_input_data.setGeometry(QtCore.QRect(20, 340, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_plot_input_data.setFont(font)
        self.pushButton_plot_input_data.setAutoFillBackground(False)
        self.pushButton_plot_input_data.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.pushButton_plot_input_data.setObjectName("pushButton_plot_input_data")
        self.label_gravity_resolution = QtWidgets.QLabel(self.centralwidget)
        self.label_gravity_resolution.setGeometry(QtCore.QRect(360, 30, 121, 16))
        self.label_gravity_resolution.setObjectName("label_gravity_resolution")
        self.message_box = QtWidgets.QTextEdit(self.centralwidget)
        self.message_box.setGeometry(QtCore.QRect(530, 410, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.message_box.setFont(font)
        self.message_box.setObjectName("message_box")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 480, 971, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_ice_resolution = QtWidgets.QLabel(self.centralwidget)
        self.label_ice_resolution.setGeometry(QtCore.QRect(360, 80, 121, 16))
        self.label_ice_resolution.setObjectName("label_ice_resolution")
        self.label_water_resolution = QtWidgets.QLabel(self.centralwidget)
        self.label_water_resolution.setGeometry(QtCore.QRect(360, 131, 121, 16))
        self.label_water_resolution.setObjectName("label_water_resolution")
        self.label_bathymetry_resolution = QtWidgets.QLabel(self.centralwidget)
        self.label_bathymetry_resolution.setGeometry(QtCore.QRect(360, 180, 121, 16))
        self.label_bathymetry_resolution.setObjectName("label_bathymetry_resolution")
        self.label_basement_resolution = QtWidgets.QLabel(self.centralwidget)
        self.label_basement_resolution.setGeometry(QtCore.QRect(360, 230, 121, 16))
        self.label_basement_resolution.setObjectName("label_basement_resolution")
        self.label_moho_resolution = QtWidgets.QLabel(self.centralwidget)
        self.label_moho_resolution.setGeometry(QtCore.QRect(360, 280, 121, 16))
        self.label_moho_resolution.setObjectName("label_moho_resolution")
        self.line_bathymetry_resolution = QtWidgets.QLineEdit(self.centralwidget)
        self.line_bathymetry_resolution.setGeometry(QtCore.QRect(360, 160, 111, 21))
        self.line_bathymetry_resolution.setObjectName("line_bathymetry_resolution")
        self.line_moho_resolution = QtWidgets.QLineEdit(self.centralwidget)
        self.line_moho_resolution.setGeometry(QtCore.QRect(360, 260, 111, 21))
        self.line_moho_resolution.setObjectName("line_moho_resolution")
        self.line_water_resolution = QtWidgets.QLineEdit(self.centralwidget)
        self.line_water_resolution.setGeometry(QtCore.QRect(360, 110, 111, 21))
        self.line_water_resolution.setObjectName("line_water_resolution")
        self.line_ice_resolution = QtWidgets.QLineEdit(self.centralwidget)
        self.line_ice_resolution.setGeometry(QtCore.QRect(360, 60, 111, 21))
        self.line_ice_resolution.setObjectName("line_ice_resolution")
        self.line_gravity_resolution = QtWidgets.QLineEdit(self.centralwidget)
        self.line_gravity_resolution.setGeometry(QtCore.QRect(360, 10, 111, 21))
        self.line_gravity_resolution.setText("")
        self.line_gravity_resolution.setObjectName("line_gravity_resolution")
        self.line_basement_resolution = QtWidgets.QLineEdit(self.centralwidget)
        self.line_basement_resolution.setGeometry(QtCore.QRect(360, 210, 111, 21))
        self.line_basement_resolution.setObjectName("line_basement_resolution")
        self.label_gridding_methods = QtWidgets.QLabel(self.centralwidget)
        self.label_gridding_methods.setGeometry(QtCore.QRect(60, 310, 191, 21))
        self.label_gridding_methods.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gridding_methods.setObjectName("label_gridding_methods")
        self.comboBox_gridding = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_gridding.setGeometry(QtCore.QRect(260, 310, 141, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_gridding.setFont(font)
        self.comboBox_gridding.setObjectName("comboBox_gridding")
        self.comboBox_gridding.addItem("")
        self.comboBox_gridding.addItem("")
        self.pushButton_plot_gravity_grids = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plot_gravity_grids.setGeometry(QtCore.QRect(20, 380, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_plot_gravity_grids.setFont(font)
        self.pushButton_plot_gravity_grids.setAutoFillBackground(False)
        self.pushButton_plot_gravity_grids.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.pushButton_plot_gravity_grids.setObjectName("pushButton_plot_gravity_grids")
        self.line_density_filtering = QtWidgets.QLineEdit(self.centralwidget)
        self.line_density_filtering.setGeometry(QtCore.QRect(800, 250, 131, 20))
        self.line_density_filtering.setAlignment(QtCore.Qt.AlignCenter)
        self.line_density_filtering.setObjectName("line_density_filtering")
        self.label_input_ice_layer_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_9.setGeometry(QtCore.QRect(534, 220, 221, 20))
        self.label_input_ice_layer_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_9.setObjectName("label_input_ice_layer_9")
        self.line_maximum_iterations = QtWidgets.QLineEdit(self.centralwidget)
        self.line_maximum_iterations.setGeometry(QtCore.QRect(580, 250, 131, 20))
        self.line_maximum_iterations.setAlignment(QtCore.Qt.AlignCenter)
        self.line_maximum_iterations.setObjectName("line_maximum_iterations")
        self.label_input_ice_layer_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_11.setGeometry(QtCore.QRect(740, 270, 241, 20))
        self.label_input_ice_layer_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_11.setObjectName("label_input_ice_layer_11")
        self.line_least_squares_tolerance = QtWidgets.QLineEdit(self.centralwidget)
        self.line_least_squares_tolerance.setGeometry(QtCore.QRect(800, 200, 131, 20))
        self.line_least_squares_tolerance.setAlignment(QtCore.Qt.AlignCenter)
        self.line_least_squares_tolerance.setObjectName("line_least_squares_tolerance")
        self.line_least_squares = QtWidgets.QLineEdit(self.centralwidget)
        self.line_least_squares.setGeometry(QtCore.QRect(580, 200, 131, 21))
        self.line_least_squares.setAlignment(QtCore.Qt.AlignCenter)
        self.line_least_squares.setObjectName("line_least_squares")
        self.label_input_ice_layer_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_10.setGeometry(QtCore.QRect(750, 220, 241, 20))
        self.label_input_ice_layer_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_10.setObjectName("label_input_ice_layer_10")
        self.label_input_ice_layer_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_12.setGeometry(QtCore.QRect(520, 270, 241, 20))
        self.label_input_ice_layer_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_12.setObjectName("label_input_ice_layer_12")
        self.pushButton_run_inversion = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_run_inversion.setEnabled(True)
        self.pushButton_run_inversion.setGeometry(QtCore.QRect(530, 380, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_run_inversion.setFont(font)
        self.pushButton_run_inversion.setAutoFillBackground(False)
        self.pushButton_run_inversion.setStyleSheet("background-color: rgb(157, 157, 157);")
        self.pushButton_run_inversion.setObjectName("pushButton_run_inversion")
        self.label_input_ice_layer_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_21.setGeometry(QtCore.QRect(530, 10, 451, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_input_ice_layer_21.setFont(font)
        self.label_input_ice_layer_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_21.setObjectName("label_input_ice_layer_21")
        self.label_input_ice_layer_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_22.setGeometry(QtCore.QRect(860, 110, 121, 20))
        self.label_input_ice_layer_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_22.setObjectName("label_input_ice_layer_22")
        self.label_input_ice_layer_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_24.setGeometry(QtCore.QRect(530, 70, 451, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_input_ice_layer_24.setFont(font)
        self.label_input_ice_layer_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_24.setObjectName("label_input_ice_layer_24")
        self.line_bathymetry_constraints_variation = QtWidgets.QLineEdit(self.centralwidget)
        self.line_bathymetry_constraints_variation.setGeometry(QtCore.QRect(530, 90, 125, 20))
        self.line_bathymetry_constraints_variation.setAlignment(QtCore.Qt.AlignCenter)
        self.line_bathymetry_constraints_variation.setObjectName("line_bathymetry_constraints_variation")
        self.line_bathymetry_variation = QtWidgets.QLineEdit(self.centralwidget)
        self.line_bathymetry_variation.setGeometry(QtCore.QRect(530, 30, 125, 20))
        self.line_bathymetry_variation.setAlignment(QtCore.Qt.AlignCenter)
        self.line_bathymetry_variation.setObjectName("line_bathymetry_variation")
        self.label_input_ice_layer_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_25.setGeometry(QtCore.QRect(530, 50, 121, 20))
        self.label_input_ice_layer_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_25.setObjectName("label_input_ice_layer_25")
        self.line_basement_variation = QtWidgets.QLineEdit(self.centralwidget)
        self.line_basement_variation.setGeometry(QtCore.QRect(690, 30, 131, 20))
        self.line_basement_variation.setAlignment(QtCore.Qt.AlignCenter)
        self.line_basement_variation.setObjectName("line_basement_variation")
        self.line_moho_constraints_variation = QtWidgets.QLineEdit(self.centralwidget)
        self.line_moho_constraints_variation.setGeometry(QtCore.QRect(860, 90, 121, 20))
        self.line_moho_constraints_variation.setAlignment(QtCore.Qt.AlignCenter)
        self.line_moho_constraints_variation.setObjectName("line_moho_constraints_variation")
        self.label_input_ice_layer_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_27.setGeometry(QtCore.QRect(690, 50, 131, 20))
        self.label_input_ice_layer_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_27.setObjectName("label_input_ice_layer_27")
        self.label_input_ice_layer_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_28.setGeometry(QtCore.QRect(860, 50, 121, 20))
        self.label_input_ice_layer_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_28.setObjectName("label_input_ice_layer_28")
        self.line_moho_variation = QtWidgets.QLineEdit(self.centralwidget)
        self.line_moho_variation.setGeometry(QtCore.QRect(860, 30, 121, 20))
        self.line_moho_variation.setAlignment(QtCore.Qt.AlignCenter)
        self.line_moho_variation.setObjectName("line_moho_variation")
        self.label_input_ice_layer_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_29.setGeometry(QtCore.QRect(530, 110, 121, 20))
        self.label_input_ice_layer_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_29.setObjectName("label_input_ice_layer_29")
        self.line_basement_constraints_variation = QtWidgets.QLineEdit(self.centralwidget)
        self.line_basement_constraints_variation.setGeometry(QtCore.QRect(690, 90, 131, 20))
        self.line_basement_constraints_variation.setAlignment(QtCore.Qt.AlignCenter)
        self.line_basement_constraints_variation.setObjectName("line_basement_constraints_variation")
        self.label_input_ice_layer_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_30.setGeometry(QtCore.QRect(690, 110, 131, 20))
        self.label_input_ice_layer_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_30.setObjectName("label_input_ice_layer_30")
        self.label_input_ice_layer_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_8.setGeometry(QtCore.QRect(690, 170, 131, 20))
        self.label_input_ice_layer_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_8.setObjectName("label_input_ice_layer_8")
        self.label_input_ice_layer_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_7.setGeometry(QtCore.QRect(530, 170, 121, 20))
        self.label_input_ice_layer_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_7.setObjectName("label_input_ice_layer_7")
        self.label_input_ice_layer_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_23.setGeometry(QtCore.QRect(860, 170, 121, 20))
        self.label_input_ice_layer_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_23.setObjectName("label_input_ice_layer_23")
        self.label_input_ice_layer_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_26.setGeometry(QtCore.QRect(540, 130, 451, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_input_ice_layer_26.setFont(font)
        self.label_input_ice_layer_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_26.setObjectName("label_input_ice_layer_26")
        self.line_mantle_density_variation = QtWidgets.QLineEdit(self.centralwidget)
        self.line_mantle_density_variation.setGeometry(QtCore.QRect(860, 150, 121, 20))
        self.line_mantle_density_variation.setAlignment(QtCore.Qt.AlignCenter)
        self.line_mantle_density_variation.setObjectName("line_mantle_density_variation")
        self.line_crust_density_variation = QtWidgets.QLineEdit(self.centralwidget)
        self.line_crust_density_variation.setGeometry(QtCore.QRect(690, 150, 131, 20))
        self.line_crust_density_variation.setAlignment(QtCore.Qt.AlignCenter)
        self.line_crust_density_variation.setObjectName("line_crust_density_variation")
        self.line_sediment_density_variation = QtWidgets.QLineEdit(self.centralwidget)
        self.line_sediment_density_variation.setGeometry(QtCore.QRect(530, 150, 125, 20))
        self.line_sediment_density_variation.setAlignment(QtCore.Qt.AlignCenter)
        self.line_sediment_density_variation.setObjectName("line_sediment_density_variation")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(490, 0, 20, 421))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_min_sed_thickness = QtWidgets.QLineEdit(self.centralwidget)
        self.line_min_sed_thickness.setGeometry(QtCore.QRect(580, 300, 131, 20))
        self.line_min_sed_thickness.setAlignment(QtCore.Qt.AlignCenter)
        self.line_min_sed_thickness.setObjectName("line_min_sed_thickness")
        self.label_input_ice_layer_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_input_ice_layer_13.setGeometry(QtCore.QRect(520, 320, 241, 20))
        self.label_input_ice_layer_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_ice_layer_13.setObjectName("label_input_ice_layer_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionInput_Gravity_Data = QtWidgets.QAction(MainWindow)
        self.actionInput_Gravity_Data.setObjectName("actionInput_Gravity_Data")
        self.actionInput_Ice_Surface = QtWidgets.QAction(MainWindow)
        self.actionInput_Ice_Surface.setObjectName("actionInput_Ice_Surface")
        self.actionInput_Water_Surface = QtWidgets.QAction(MainWindow)
        self.actionInput_Water_Surface.setObjectName("actionInput_Water_Surface")
        self.actionInput_Bathymetry = QtWidgets.QAction(MainWindow)
        self.actionInput_Bathymetry.setObjectName("actionInput_Bathymetry")
        self.actionInput_Basement_Surface = QtWidgets.QAction(MainWindow)
        self.actionInput_Basement_Surface.setObjectName("actionInput_Basement_Surface")
        self.actionInput_Moho = QtWidgets.QAction(MainWindow)
        self.actionInput_Moho.setObjectName("actionInput_Moho")
        self.actionRun_Forward_Gravity_Model = QtWidgets.QAction(MainWindow)
        self.actionRun_Forward_Gravity_Model.setObjectName("actionRun_Forward_Gravity_Model")
        self.actionRun_Density_Inversion = QtWidgets.QAction(MainWindow)
        self.actionRun_Density_Inversion.setObjectName("actionRun_Density_Inversion")
        self.actionClear_Memory = QtWidgets.QAction(MainWindow)
        self.actionClear_Memory.setObjectName("actionClear_Memory")
        self.actionExit_Program = QtWidgets.QAction(MainWindow)
        self.actionExit_Program.setObjectName("actionExit_Program")
        self.actionSave_Input_Files = QtWidgets.QAction(MainWindow)
        self.actionSave_Input_Files.setObjectName("actionSave_Input_Files")
        self.actionLoad_Saved_Input_Files = QtWidgets.QAction(MainWindow)
        self.actionLoad_Saved_Input_Files.setObjectName("actionLoad_Saved_Input_Files")
        self.menuFile.addAction(self.actionInput_Gravity_Data)
        self.menuFile.addAction(self.actionInput_Ice_Surface)
        self.menuFile.addAction(self.actionInput_Water_Surface)
        self.menuFile.addAction(self.actionInput_Bathymetry)
        self.menuFile.addAction(self.actionInput_Basement_Surface)
        self.menuFile.addAction(self.actionInput_Moho)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionRun_Forward_Gravity_Model)
        self.menuFile.addAction(self.actionRun_Density_Inversion)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoad_Saved_Input_Files)
        self.menuFile.addAction(self.actionSave_Input_Files)
        self.menuFile.addAction(self.actionClear_Memory)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.line_gravity_resolution, self.line_ice_resolution)
        MainWindow.setTabOrder(self.line_ice_resolution, self.line_water_resolution)
        MainWindow.setTabOrder(self.line_water_resolution, self.line_bathymetry_resolution)
        MainWindow.setTabOrder(self.line_bathymetry_resolution, self.line_basement_resolution)
        MainWindow.setTabOrder(self.line_basement_resolution, self.line_moho_resolution)
        MainWindow.setTabOrder(self.line_moho_resolution, self.line_bathymetry_variation)
        MainWindow.setTabOrder(self.line_bathymetry_variation, self.line_basement_variation)
        MainWindow.setTabOrder(self.line_basement_variation, self.line_moho_variation)
        MainWindow.setTabOrder(self.line_moho_variation, self.line_bathymetry_constraints_variation)
        MainWindow.setTabOrder(self.line_bathymetry_constraints_variation, self.line_basement_constraints_variation)
        MainWindow.setTabOrder(self.line_basement_constraints_variation, self.line_moho_constraints_variation)
        MainWindow.setTabOrder(self.line_moho_constraints_variation, self.line_sediment_density_variation)
        MainWindow.setTabOrder(self.line_sediment_density_variation, self.line_crust_density_variation)
        MainWindow.setTabOrder(self.line_crust_density_variation, self.line_mantle_density_variation)
        MainWindow.setTabOrder(self.line_mantle_density_variation, self.line_least_squares)
        MainWindow.setTabOrder(self.line_least_squares, self.line_least_squares_tolerance)
        MainWindow.setTabOrder(self.line_least_squares_tolerance, self.line_maximum_iterations)
        MainWindow.setTabOrder(self.line_maximum_iterations, self.line_density_filtering)
        MainWindow.setTabOrder(self.line_density_filtering, self.line_min_sed_thickness)
        MainWindow.setTabOrder(self.line_min_sed_thickness, self.pushButton_run_inversion)
        MainWindow.setTabOrder(self.pushButton_run_inversion, self.pushButton_plot_gravity_grids)
        MainWindow.setTabOrder(self.pushButton_plot_gravity_grids, self.comboBox_gridding)
        MainWindow.setTabOrder(self.comboBox_gridding, self.line_input_moho_file)
        MainWindow.setTabOrder(self.line_input_moho_file, self.line_input_basement_surface_file)
        MainWindow.setTabOrder(self.line_input_basement_surface_file, self.line_input_water_surface_file)
        MainWindow.setTabOrder(self.line_input_water_surface_file, self.line_input_bathymetry_file)
        MainWindow.setTabOrder(self.line_input_bathymetry_file, self.line_gravity_size)
        MainWindow.setTabOrder(self.line_gravity_size, self.line_basement_size)
        MainWindow.setTabOrder(self.line_basement_size, self.line_bathymetry_size)
        MainWindow.setTabOrder(self.line_bathymetry_size, self.line_ice_size)
        MainWindow.setTabOrder(self.line_ice_size, self.pushButton_plot_input_data)
        MainWindow.setTabOrder(self.pushButton_plot_input_data, self.line_water_size)
        MainWindow.setTabOrder(self.line_water_size, self.line_moho_size)
        MainWindow.setTabOrder(self.line_moho_size, self.line_input_ice_surface_file)
        MainWindow.setTabOrder(self.line_input_ice_surface_file, self.line_input_gravity_data_file)
        MainWindow.setTabOrder(self.line_input_gravity_data_file, self.message_box)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_input_gravity_data_file.setText(_translate("MainWindow", "Input gravity data file"))
        self.label_ice_surface_file.setText(_translate("MainWindow", "Input ice surface file"))
        self.label_input_water_surface_file.setText(_translate("MainWindow", "Input water surface file"))
        self.label_bathymetry_file.setText(_translate("MainWindow", "Input bathymetry file"))
        self.label_input_basement_file.setText(_translate("MainWindow", "Input basement surface  file"))
        self.label_input_moho_file.setText(_translate("MainWindow", "Input moho file"))
        self.label_gravity_size.setText(_translate("MainWindow", "# of points"))
        self.label_bathymetry_size.setText(_translate("MainWindow", "# of points"))
        self.label_ice_size.setText(_translate("MainWindow", "# of points"))
        self.label_water_size.setText(_translate("MainWindow", "# of points"))
        self.label_basement_size.setText(_translate("MainWindow", "# of points"))
        self.label_moho_size.setText(_translate("MainWindow", "# of points"))
        self.pushButton_plot_input_data.setText(_translate("MainWindow", "Plot input data"))
        self.label_gravity_resolution.setText(_translate("MainWindow", "Input resolution (m)"))
        self.label_ice_resolution.setText(_translate("MainWindow", "Input resolution (m)"))
        self.label_water_resolution.setText(_translate("MainWindow", "Input resolution (m)"))
        self.label_bathymetry_resolution.setText(_translate("MainWindow", "Input resolution (m)"))
        self.label_basement_resolution.setText(_translate("MainWindow", "Input resolution (m)"))
        self.label_moho_resolution.setText(_translate("MainWindow", "Input resolution (m)"))
        self.label_gridding_methods.setText(_translate("MainWindow", "Model for regional gravity field:"))
        self.comboBox_gridding.setItemText(0, _translate("MainWindow", "Constant value"))
        self.comboBox_gridding.setItemText(1, _translate("MainWindow", "Linear trend"))
        self.pushButton_plot_gravity_grids.setText(_translate("MainWindow", "Plot observed, residual, and regional gravity grids"))
        self.line_density_filtering.setText(_translate("MainWindow", "0"))
        self.label_input_ice_layer_9.setText(_translate("MainWindow", "Least-squares norm"))
        self.line_maximum_iterations.setText(_translate("MainWindow", "50"))
        self.label_input_ice_layer_11.setText(_translate("MainWindow", "Density inversion filtering"))
        self.line_least_squares_tolerance.setText(_translate("MainWindow", "0.02"))
        self.line_least_squares.setText(_translate("MainWindow", "0.001"))
        self.label_input_ice_layer_10.setText(_translate("MainWindow", "Tolerance on least-squares norm"))
        self.label_input_ice_layer_12.setText(_translate("MainWindow", "Maximum number of iterations"))
        self.pushButton_run_inversion.setText(_translate("MainWindow", "Run gravity inversion"))
        self.label_input_ice_layer_21.setText(_translate("MainWindow", "Max surface elevation change per iteration (m)"))
        self.label_input_ice_layer_22.setText(_translate("MainWindow", "Moho"))
        self.label_input_ice_layer_24.setText(_translate("MainWindow", "Max surface elevation change at constraints during inversion (m) "))
        self.line_bathymetry_constraints_variation.setText(_translate("MainWindow", "0"))
        self.line_bathymetry_variation.setText(_translate("MainWindow", "0"))
        self.label_input_ice_layer_25.setText(_translate("MainWindow", "Bathymetry"))
        self.line_basement_variation.setText(_translate("MainWindow", "0"))
        self.line_moho_constraints_variation.setText(_translate("MainWindow", "0"))
        self.label_input_ice_layer_27.setText(_translate("MainWindow", "Basement"))
        self.label_input_ice_layer_28.setText(_translate("MainWindow", "Moho"))
        self.line_moho_variation.setText(_translate("MainWindow", "0"))
        self.label_input_ice_layer_29.setText(_translate("MainWindow", "Bathymetry"))
        self.line_basement_constraints_variation.setText(_translate("MainWindow", "0"))
        self.label_input_ice_layer_30.setText(_translate("MainWindow", "Basement"))
        self.label_input_ice_layer_8.setText(_translate("MainWindow", "Crust"))
        self.label_input_ice_layer_7.setText(_translate("MainWindow", "Sediment"))
        self.label_input_ice_layer_23.setText(_translate("MainWindow", "Mantle"))
        self.label_input_ice_layer_26.setText(_translate("MainWindow", "Max density change per iteration (g/cm^3)"))
        self.line_mantle_density_variation.setText(_translate("MainWindow", "0.0"))
        self.line_crust_density_variation.setText(_translate("MainWindow", "0.0"))
        self.line_sediment_density_variation.setText(_translate("MainWindow", "0.0"))
        self.line_min_sed_thickness.setText(_translate("MainWindow", "50"))
        self.label_input_ice_layer_13.setText(_translate("MainWindow", "Min Sediment Thickness (m)"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionInput_Gravity_Data.setText(_translate("MainWindow", "Input Gravity Data"))
        self.actionInput_Ice_Surface.setText(_translate("MainWindow", "Input Ice Surface "))
        self.actionInput_Water_Surface.setText(_translate("MainWindow", "Input Water Surface"))
        self.actionInput_Bathymetry.setText(_translate("MainWindow", "Input Bathymetry"))
        self.actionInput_Basement_Surface.setText(_translate("MainWindow", "Input Basement Surface"))
        self.actionInput_Moho.setText(_translate("MainWindow", "Input Moho"))
        self.actionRun_Forward_Gravity_Model.setText(_translate("MainWindow", "Run Forward Gravity Model"))
        self.actionRun_Density_Inversion.setText(_translate("MainWindow", "Run Density Inversion"))
        self.actionClear_Memory.setText(_translate("MainWindow", "Clear Memory"))
        self.actionExit_Program.setText(_translate("MainWindow", "Exit Program"))
        self.actionSave_Input_Files.setText(_translate("MainWindow", "Save Input Files"))
        self.actionLoad_Saved_Input_Files.setText(_translate("MainWindow", "Load Saved Input Files"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

