name: RIS_gravity_inversion
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pygmt
  - geopandas
  - geoviews
  - numpy
  - pandas
  - snakeviz
  - scipy
  - matplotlib
  - pyvista
  - pyvista-xarray
  - harmonica
  - verde
  - xarray
  - tqdm
  - rioxarray
  - openssl
  - seaborn
  - ipyvtklink
  - ipykernel
  - proj-data
  - cmocean
  - numba
  - pip
  - pip:
    - numba-progress
    - --editable ../../antarctic_plots
