name: RIS_gravity_inversion
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pygmt
  - geopandas
  - geoviews
  - numpy
  - pandas
  - snakeviz
  - scipy
  - matplotlib
  - pyvista
  - pyvista-xarray
  - harmonica
  - verde>=1.8.0
  - xarray
  - tqdm
  - rioxarray
  - seaborn
  - ipykernel
  - cmocean
  - numba
  - optuna
  - boule
  - botorch<0.8.0
  - plotly
  - hvplot
  - jupyter_bokeh
  - jupyterlab
  - jupyterlab_execute_time
  - isort
  - pytest
  - pytest-cov
  - python-dotenv
  - mamba
  - pip
  - pip:
    # - git+https://github.com/fatiando/verde
    # - git+https://github.com/mdtanker/antarctic_plots
    - numba-progress
    - tqdm-joblib
    - jupyter-server-proxy
    - trame
    - flake8-pyproject
    - black[jupyter]
    - constrained-linear-regression
    - --editable ../
    - --editable ../../antarctic_plots